@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Seller" as Seller #red

participant "Seller Portal" as SystemS

participant "Stellar Horizon" as Stellar

participant "BH Tokenization" as Tokenizer
participant "User's registry" as Registry

participant "Goods Assets Tokenization \nSmart Contract" as ContractG

note over Seller, ContractD #AAFFFF: Create Goods by the Seller.
autonumber 2.1
Seller -> SystemS : Explorer available\ndemands
SystemS -> Tokenizer : Fetch list of\navailable demands
Tokenizer -> Registry : Fetch list of available\nDemand Assets Tokens
Registry --> Tokenizer : List of available\nDemand Assets Tokens
Tokenizer --> SystemS : List of available\nDemand Assets Tokens
SystemS --> Seller : Show list of available\nDemand Assets Tokens
Seller -> SystemS : Select demand\nto provide goods
SystemS --> Seller : Show a form\nto create goods
Seller -> SystemS : Create goods\nto meet the demand\nrequirements
SystemS -> Tokenizer : Register new Goods
Tokenizer -> ContractG : Create new\nDemand Assets Token
ContractG --> ContractG : Issue new Asset\nStore Goods data in\nSoroban persistent store
ContractG --> Tokenizer : Goods Asset information Asset code, Asset issuer
Tokenizer -> Registry : Register new Goods\nfor the Seller
Registry --> Tokenizer : Success
Tokenizer --> Tokenizer : Link Goods Asset to\nBuyer's Demand
Tokenizer --> SystemS : Goods Asset information
SystemS --> Seller : Success

@enduml