@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Buyer as Buyer #green
actor "Seller" as Seller #red

participant "Buyer Portal" as SystemD
participant "Seller Portal" as SystemS

participant "Stellar Horizon" as Stellar

participant "BH Tokenization" as Tokenizer
participant "User's registry" as Registry

participant "Purchasing Asset Tokenization \nSmart Contract" as ContractP
participant "Demand Asset Tokenization \nSmart Contract" as ContractD
participant "Goods Asset Tokenization \nSmart Contract" as ContractG
participant "Stellar Anchor platform" as Anchor


note over Buyer, ContractD #AAFF33: Buy Goods for the Demand.
autonumber 3.1
Buyer -> SystemD : Get a list\nof Goods Asset linked\nwith Demand Asset
SystemD -> Stellar : Fetch a list of\nGoods Asset\nlinked with\nDemand Asset
Stellar --> SystemD : Return list of Goods Asset\nlinked with\nDemand Asset
SystemD --> Buyer : Show List of\nGoods Asset\nlinked with\nDemand Asset
Buyer -> SystemD : Select Goods to buy
SystemD -> Tokenizer : Create Purchasing Asset\n to buy the goods
Tokenizer -> ContractP : Create new Purchasing Asset\n to buy the goods
ContractP --> ContractP : Issue new Asset\nStore purchasing data in\nSoroban persistent store
ContractP --> Tokenizer : Purchasing Asset information Asset code, Asset issuer
Tokenizer -> ContractD : Get linked TOML file
ContractD --> Tokenizer : Return TOML file
Tokenizer --> Tokenizer : Get payment methods\ninformation from linked\nTOML file
Tokenizer --> SystemD : Return Purchasing Asset information Asset code, Asset issuer\npayment method link
SystemD --> Buyer : Redirect to payment method
Buyer -> Anchor : Fill payment information and process payment
Anchor -> Stellar : Transfer Asset as a payment result
Stellar -> Tokenizer : Asset received
Tokenizer -> ContractP : Mint the Purchasing Asset Token with received amount
ContractP -> ContractP : Update Purchasing Asset Token\nwith payment information
ContractP --> Tokenizer : Success
Tokenizer --> ContractP : Transfer Purchasing\nAsset Tokens\nto Seller
ContractP --> ContractP : Transfer Purchasing\nAsset Tokens to Seller\nupdate Soroban persistent store\nwith transfer information
Tokenizer --> SystemD : Success
SystemD --> Buyer : Success
Seller -> Buyer : Deliver Goods\nfor the Demand
alt
autonumber 3.25.1.1
Buyer -> SystemD : Confirm Goods Delivery
SystemD -> Tokenizer : Confirm Goods Delivery
Tokenizer --> ContractP : Approve Transfer of Purchasing Asset Tokens
ContractP --> ContractP : Swap Purchasing Asset Tokens to Payout Asset\nBurn Purchasing Asset Tokens
ContractP --> Tokenizer : Success
Tokenizer -> ContractG : Burn Goods Asset Tokens
ContractG --> Tokenizer : Success
Tokenizer -> ContractD : Burn Demand Asset Tokens
ContractD --> Tokenizer : Success
Tokenizer --> SystemD : Success
SystemD --> Buyer : Success
else
autonumber 3.25.2.1
Buyer -> SystemD : Fail of Goods Delivery
SystemD -> Tokenizer : Fail of  Goods Delivery
Tokenizer --> ContractP : Reject Transfer of Purchasing Asset Tokens
Tokenizer --> Tokenizer : Revert Purchasing\nAsset to Buyer\naccount
Tokenizer --> SystemD : Success
SystemD --> Buyer : Success
end

@enduml